[project]
site_name = "PARE - Planificación y Administración de Redes y Equipos"
site_url = "https://raul-profesor.github.io/sostenibilidadº"
dev_addr = "localhost:9090"
extra_css = ["stylesheets/extra.css"]
# Tema Material
nav = [
    {Home = "index.md"},
    {Unidad1 = [
        "Resumen_extenso_UD1.md",
    ]},
    {Unidad2 = [
        "Resumen_extenso_UD2.md",
    ]}
]

[project.theme]
name = "material"
language = "es"
font.text = "Inter"

features = [
    "navigation.instant",
    "navigation.instant",
    "navigation.instant.progress",
    "navigation.tabs",
    "navigation.expand",
    "navigation.path",
    "toc.follow",
    "navigation.top",
    "content.footnote.tooltips"
]
# Configuración de paletas de colores
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "blue"
toggle.icon = "lucide/sun"
toggle.name = "Cambiar a modo oscuro"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "black"
accent = "deep orange"
toggle.icon = "lucide/moon"
toggle.name = "Cambiar a modo claro"

[project.theme.icon.admonition]
note = "lucide/notebook"
abstract = "lucide/book-open"
info = "lucide/info"
tip = "lucide/lightbulb"
success = "lucide/circle-check"
question = "lucide/circle-help"
warning = "lucide/triangle-alert"
failure = "lucide/circle-x"
danger = "lucide/shield-alert"
bug = "lucide/bug"
example = "lucide/flask-conical"
quote = "lucide/quote"

[project.markdown_extensions]
abbr = {}
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.blocks.caption] 
types = [
    "caption",
    "table",
    "figure",
    { name = "figura", prefix = "Figura {}. " }
]
auto=true

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
